### ISSUE TITLE
need to update 

### ISSUE THREAD

**Issue by aboali19** [matthayes/anki_flex_dupes#6]
this helpful addon is still worth a try to update with the new versions (Anki 2.1.50 and higher)

**Comment by alproo** [comment]
Alas add-on does not seem to work with my v.2.1.52 as well. Despite having just made my first steps into coding I am more than willing to contribute. If I may be of help with anything. The add-on is of vital importance to me.

**Comment by hedgss** [comment]
It stop working on anki-2.1.54-windows-qt6
```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Flexible Duplicate Checking⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\<User>\AppData\Roaming\Anki2\addons21\1587955871\__init__.py", line 19, in <module>
    setup()
  File "C:\Users\<User>\AppData\Roaming\Anki2\addons21\1587955871\flex_dupe_checking\__init__.py", line 154, in setup
    Editor._links["dupes"] = showDupes
AttributeError: type object 'Editor' has no attribute '_links
```

**Comment by sun3alex** [comment]
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Flexible Duplicate Checking⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/alexkoi/Library/Application Support/Anki2/addons21/1587955871/__init__.py", line 19, in <module>
    setup()
  File "/Users/alexkoi/Library/Application Support/Anki2/addons21/1587955871/flex_dupe_checking/__init__.py", line 154, in setup
    Editor._links["dupes"] = showDupes
AttributeError: type object 'Editor' has no attribute '_links'
